site_name: Yor name 
site_url: https://mylab3.com

theme:
    name: material

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
 - Лабораторная работа №3: index.md