# Generated by Django 4.1.5 on 2023-01-18 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0012_remove_user_photo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="date",
            new_name="date_time",
        ),
    ]
