# Generated by Django 4.1.5 on 2023-01-18 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0013_rename_date_event_date_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="date",
            field=models.DateField(default="2022-11-02"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="time",
            field=models.TimeField(default="19:00"),
            preserve_default=False,
        ),
    ]
