# Generated by Django 4.1.5 on 2023-01-18 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0014_event_date_event_time"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="name",
            new_name="title",
        ),
        migrations.RemoveField(
            model_name="event",
            name="date_time",
        ),
    ]
