site_name: Kirillova Vika, K33402

theme:
  name: material

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  
nav:
 - Главная: index.md
 - Лабораторная работа №1: Lr_1.md
 - Лабораторная работа №2: Lr_2.md
 - Лабораторная работа №3: Lr_3.md
 